# This workflow deploys a static website directly to GitHub Pages.
# It is triggered whenever you push to the 'main' branch.

name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # Set your main branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from your repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy the files to the 'gh-pages' branch.
      # The `publish_dir` is set to a single dot (`.`)
      # because your index.html file is in the root of the repository.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages # This is the branch where the static files will be hosted
